apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-assistant
  template:
    metadata:
      labels:
        app: music-assistant
    spec:
      nodeSelector:
        node-type: local
      containers:
        - name: music-assistant
          image: ghcr.io/music-assistant/server:2.6.0
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "4"
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - DAC_READ_SEARCH
            seccompProfile:
              type: Unconfined
          ports:
            - containerPort: 8095
          volumeMounts:
            - name: music-assistant
              mountPath: /data
          env:
            - name: LOG_LEVEL
              value: "info"
      volumes:
        - name: music-assistant
          persistentVolumeClaim:
            claimName: music-assistant
