- name: Apply configure_ssh role on rpi5
  hosts: rpi5
  gather_facts: false
  vars:
    ansible_host_key_checking: false
  roles:
    - configure_ssh

- name: Apply home_nas role on rpi5
  hosts: rpi5
  roles:
    - rpi_upgrade
    - home_nas
