- name: Apply configure_ssh role on rpi3
  hosts: rpi3
  gather_facts: false
  vars:
    ansible_host_key_checking: false
  roles:
    - configure_ssh

- name: Apply home_runner role on rpi3
  hosts: rpi3
  roles:
    - rpi_upgrade
    - home_runner
