---
roles:
  - name: monolithprojects.github_actions_runner
  - name: geerlingguy.docker
  - name: geerlingguy.ansible
  - name: geerlingguy.certbot
  - name: xanmanning.k3s
  - name: geerlingguy.nfs
  - name: geerlingguy.pip
  - name: geerlingguy.helm
  - name: geerlingguy.git

collections:
  - name: kubernetes.core
  - name: community.docker
  - name: community.grafana
  - name: ansible.posix
  - name: prometheus.prometheus
