---
roles:
  - name: monolithprojects.github_actions_runner

collections:
  - name: kubernetes.core
    version: ">=6.0.0"
  - name: community.docker
    version: ">=5.2.2"
  - name: community.grafana
    version: ">=2.3.0"
  - name: ansible.posix
    version: ">=2.2.2"
  - name: prometheus.prometheus
    version: ">=0.30.1"
