apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: duplicati
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app.kubernetes.io/name: duplicati
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
