- name: Run the equivalent of "apt-get update"
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Update all packages to the latest version
  become: true
  ansible.builtin.apt:
    upgrade: full
