- name: Create Github Actions Runner configuration directory
  ansible.builtin.file:
    path: "{{ '/home/' + ansible_user + '/github_actions_runner' }}"
    state: directory
    mode: "755"

- name: Install GitHub Actions Runner
  become: true
  vars:
    github_account: ncasaux
    github_repo: home-lab
    runner_user: "{{ inventory_hosts.rpi4.user }}"
    access_token: "{{ home_gateway_github_access_token }}"
  tags: runner
  ansible.builtin.import_role:
    name: ansible-github_actions_runner
