apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: http://pajikos.github.io/home-assistant-helm-chart
    chart: home-assistant
    targetRevision: '*'
    helm:
      valuesObject:
        nodeSelector:
          kubernetes.io/hostname: rpi-cm4-4
        securityContext:
          privileged: true
        configuration:
          enabled: true
        persistence:
          enabled: true
          storageClass: nfs-client
          matchLabels:
            app.kubernetes.io/name: home-assistant
          size: 5Gi
        ingress:
          enabled: true
          hosts:
            - host: home-assistant.nkzo.ovh
              paths:
                - path: /
                  pathType: Prefix
        additionalVolumes:
          - hostPath:
              path: /dev/serial/by-id/usb-RFXCOM_RFXtrx433XL_DO3HR29T-if00-port0
              type: CharDevice
            name: rfxcom
        additionalMounts:
          - mountPath: /dev/ttyUSB0
            name: rfxcom
        initContainers:
          - name: init-hacs
            image: bash
            command: ["bash", "-c", "cd /config && wget -O - https://get.hacs.xyz | bash -"]
            volumeMounts:
              - mountPath: /config
                name: home-assistant
        resources:
          requests:
            memory: "1G"
            cpu: "1"
          limits:
            memory: "2G"
            cpu: "4"
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
  syncPolicy:
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=false
