apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-external-provisioner
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    chart: nfs-subdir-external-provisioner
    targetRevision: '*'
    helm:
      valuesObject:
        nodeSelector:
          node-type: local
        nfs:
          path: /mnt/ssd
          server: rpi-cm4-1
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-system
  syncPolicy:
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
