apiVersion: apps/v1
kind: Deployment
metadata:
  name: duplicati
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duplicati
  template:
    metadata:
      labels:
        app: duplicati
    spec:
      nodeSelector:
        node-type: local
      containers:
        - name: duplicati
          image: lscr.io/linuxserver/duplicati:2.1.0
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8200
              name: web
          volumeMounts:
            - name: ssd
              mountPath: /config
              subPath: duplicati
            - name: ssd
              mountPath: /source
            - name: duplicati-backups
              mountPath: /backups
          env:
            - name: DUPLICATI__WEBSERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: duplicati-credentials
                  key: admin-password
            - name: TZ
              value: "Europe/Paris"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
      volumes:
        - name: ssd
          persistentVolumeClaim:
            claimName: duplicati
        - name: duplicati-backups
          emptyDir: {}
