- name: Create duplicati namespace
  when: k3s_control_node is defined and k3s_control_node
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: duplicati

- name: Create duplicati directory
  when: k3s_control_node is defined and k3s_control_node
  ansible.builtin.file:
    path: /mnt/ssd/duplicati
    state: directory
    mode: "777"

- name: Create persistent volume for Duplicati
  when: k3s_control_node is defined and k3s_control_node
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: duplicati
        labels:
          app.kubernetes.io/name: duplicati
      spec:
        storageClassName: nfs-client
        capacity:
          storage: 5Gi
        accessModes:
          - ReadWriteOnce
        nfs:
          server: "{{ inventory_hostname }}"
          path: /mnt/ssd

- name: Create Argo CD Application for Duplicati
  when: k3s_control_node is defined and k3s_control_node
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: duplicati
        namespace: argo-cd
      spec:
        project: default
        source:
          repoURL: https://github.com/ncasaux/home-lab
          path: roles/home_cluster/files/kubernetes/duplicati
          targetRevision: main
        destination:
          server: https://kubernetes.default.svc
          namespace: duplicati
        syncPolicy:
          retry:
            limit: 2
            backoff:
              duration: 5s
              maxDuration: 3m0s
              factor: 2
          automated:
            prune: false
            selfHeal: false
          syncOptions:
            - CreateNamespace=false
