- name: Install Helm on K3s server node
  when: k3s_control_node is defined and k3s_control_node
  vars:
    helm_platform: linux
    helm_arch: arm64
    helm_version: v3.17.0
  ansible.builtin.import_role:
    name: geerlingguy.helm

- name: Install Git on K3s server node
  when: k3s_control_node is defined and k3s_control_node
  become: true
  ansible.builtin.import_role:
    name: geerlingguy.git

- name: Install Helm Diff on K3s server node
  when: k3s_control_node is defined and k3s_control_node
  kubernetes.core.helm_plugin:
    plugin_path: "https://github.com/databus23/helm-diff"
    plugin_version: v3.9.14
    state: present
