- name: Create home-assistant namespace
  when: k3s_control_node is defined and k3s_control_node
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: home-assistant

- name: Create home-assistant directory
  when: k3s_control_node is defined and k3s_control_node
  ansible.builtin.file:
    path: /mnt/ssd/home-assistant
    state: directory
    mode: "777"

- name: Create persistent volume for Home Assistant
  when: k3s_control_node is defined and k3s_control_node
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: home-assistant
        labels:
          app.kubernetes.io/name: home-assistant
      spec:
        storageClassName: nfs-client
        capacity:
          storage: 5Gi
        accessModes:
          - ReadWriteOnce
        nfs:
          server: "{{ inventory_hostname }}"
          path: /mnt/ssd/home-assistant

- name: Create Argo CD Application for Home Assistant
  when: k3s_control_node is defined and k3s_control_node
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: home-assistant
        namespace: argo-cd
      spec:
        project: default
        source:
          repoURL: http://pajikos.github.io/home-assistant-helm-chart
          chart: home-assistant
          targetRevision: '*'
          helm:
            valuesObject:
              nodeSelector:
                kubernetes.io/hostname: rpi-cm4-4
              securityContext:
                privileged: true
              configuration:
                enabled: true
              persistence:
                enabled: true
                storageClass: nfs-client
                matchLabels:
                  app.kubernetes.io/name: home-assistant
                size: 5Gi
              ingress:
                enabled: true
                hosts:
                  - host: home-assistant.nkzo.ovh
                    paths:
                      - path: /
                        pathType: Prefix
              additionalVolumes:
                - hostPath:
                    path: /dev/serial/by-id/usb-RFXCOM_RFXtrx433XL_DO3HR29T-if00-port0
                    type: CharDevice
                  name: rfxcom
                - hostPath:
                    path: /dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_6c6a3cc274d9ee11b056b54c37b89984-if00-port0
                    type: CharDevice
                  name: sonoff-zigbee
              additionalMounts:
                - mountPath: /dev/ttyUSB0
                  name: rfxcom
                - mountPath: /dev/ttyUSB1
                  name: sonoff-zigbee
              additionalPorts:
                - name: dlna
                  containerPort: 5555
                  protocol: TCP
              additionalServices:
                - name: dlna
                  port: 5555
                  targetPort: dlna
                  protocol: TCP
              initContainers:
                - name: init-hacs
                  image: bash
                  command: ["bash", "-c", "cd /config && wget -O - https://get.hacs.xyz | bash -"]
                  volumeMounts:
                    - mountPath: /config
                      name: home-assistant
              resources:
                requests:
                  memory: "1G"
                  cpu: "1"
                limits:
                  memory: "2G"
                  cpu: "4"
        destination:
          server: https://kubernetes.default.svc
          namespace: home-assistant
        syncPolicy:
          retry:
            limit: 2
            backoff:
              duration: 5s
              maxDuration: 3m0s
              factor: 2
          automated:
            prune: false
            selfHeal: false
          syncOptions:
            - CreateNamespace=false
