- name: Create '.kube' folder on K3s server node
  when: k3s_control_node is defined and k3s_control_node
  ansible.builtin.file:
    path: "{{ '/home/' + ansible_user + '/.kube' }}"
    state: directory
    mode: "755"

- name: Copy config file from K3s server node to home user for Helm
  when: k3s_control_node is defined and k3s_control_node
  become: true
  ansible.builtin.copy:
    src: "/etc/rancher/k3s/k3s.yaml"
    remote_src: true
    dest: "{{ '/home/' + ansible_user + '/.kube/config' }}"
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: "644"
