- name: Fetch config file from K3s server node
  become: true
  when: k3s_control_node is defined and k3s_control_node
  run_once: true
  ansible.builtin.fetch:
    src: "/etc/rancher/k3s/k3s.yaml"
    dest: "{{ lookup('env', 'HOME') + '/.kube/config' }}"
    flat: true

- name: Replace "127.0.0.1" with K3s server node hostname
  delegate_to: localhost
  when: k3s_control_node is defined and k3s_control_node
  run_once: true
  ansible.builtin.replace:
    path: "{{ lookup('env', 'HOME') + '/.kube/config' }}"
    regexp: '^(\s*server\s*:\s*https?:\/\/).*(:\d*)\s*$'
    replace: '\1{{ inventory_hostname }}\2'
