- name: Create '/mnt/ssd' folder on K3s server node
  when: k3s_control_node is defined and k3s_control_node
  become: true
  ansible.builtin.file:
    path: /mnt/ssd
    state: directory
    owner: root
    group: root
    mode: "777"

- name: Mount '/mnt/ssd' folder on K3s server node
  when: k3s_control_node is defined and k3s_control_node
  become: true
  ansible.posix.mount:
    src: /dev/nvme0n1p1
    path: /mnt/ssd
    fstype: ext4
    opts: defaults,noatime
    state: mounted

- name: Install NFS server on K3s server node
  when: k3s_control_node is defined and k3s_control_node
  become: true
  vars:
    nfs_exports: ["/mnt/ssd *(rw,no_subtree_check,no_root_squash)"]
  ansible.builtin.import_role:
    name: geerlingguy.nfs

- name: Install NFS client
  ansible.builtin.apt:
    name: nfs-common

- name: Create Argo CD Application for NFS Subdir External Provisioner
  when: k3s_control_node is defined and k3s_control_node
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: nfs-subdir-external-provisioner
        namespace: argo-cd
      spec:
        project: default
        source:
          repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
          chart: nfs-subdir-external-provisioner
          targetRevision: '*'
          helm:
            valuesObject:
              nodeSelector:
                node-type: local
              nfs:
                path: /mnt/ssd
                server: rpi-cm4-1
        destination:
          server: https://kubernetes.default.svc
          namespace: nfs-system
        syncPolicy:
          retry:
            limit: 2
            backoff:
              duration: 5s
              maxDuration: 3m0s
              factor: 2
          automated:
            prune: false
            selfHeal: false
          syncOptions:
            - CreateNamespace=true
