apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openthread-border-router
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app.kubernetes.io/name: openthread-border-router
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
