name: Update Home Gateway Certbot

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - roles/home_gateway/tasks/install_certbot.yml

jobs:
  run-ansible-playbook:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Ansible requirements
        run: |
          ansible-galaxy role install -r requirements.yml --force
          ansible-galaxy collection install -r requirements.yml --upgrade

      - name: Run Ansible tasks
        run: |
          ansible-playbook home-gateway.yml \
            -i inventory.yml \
            --extra-vars "@~/github_actions_runner/ansible-passwords.yml" \
            --tags "certbot"
